#!/usr/bin/perl 
use strict;
use File::Basename;

if (!scalar(@ARGV) or ! -e $ARGV[0]) 
{
        print "Drop some files to create a tgz archive\n";
        exit;
}
        
my $cmd = "/usr/bin/tar cvfz ";

# Get enclosing folder of first file
my($fn, $directory) = fileparse($ARGV[0]);

# Change to that directory
chdir($directory);

# Archive is created there
my $dest_path = "Archive.tgz";
        
my $files;
foreach(@ARGV)
{
        if (!$_ or ! -e $_) { next; }
        my($filename, $directory) = fileparse($_);
        $files .= "'$filename' ";
}

print $cmd . "\n";
system("$cmd $dest_path $files");
