#!/bin/sh

	echo "PROGRESS:0"
	echo "Doing something"
	sleep 1
	echo "PROGRESS:10"
	sleep 1
	echo "PROGRESS:20"
	sleep 1
	echo "PROGRESS:30"
	sleep 1
	echo "Doing something else"
	echo "PROGRESS:40"
	sleep 1
	echo "PROGRESS:50"
	sleep 1
	echo "PROGRESS:60"
	sleep 1
	echo "Ano now for something completely different"
	echo "PROGRESS:70"
	sleep 1
	echo "PROGRESS:80"
	sleep 1
	echo "PROGRESS:90"
	sleep 1
	echo "PROGRESS:100"
	echo "Done"
